module.exports.config = {
    // WHICH CHANNELS TO LISTEN TO
    CHANNELS: ["kendinemuzisyen", "jahrein", "levo", "haskologlu", "wtcn", "surhaybakis", "hasanabi", "elraenn", "haruncan", "hype"],

    // WHETHER TO APPLY FILTERING FOR KEYWORDS (USES FUZZY SEARCH NOT EXACT MATCH)
    KEYWORD_MATCH: true,

    // WHETHER TO APPLY FILTERING FOR CITY NAMES (USES FUZZY SEARCH NOT EXACT MATCH)
    CITY_MATCH: true,

    // NOTIFY SERVICE URL
    NOTIFY_URL: 'https://dweet.io/dweet/for/twitch-deprem-adres-test',
    // NOTE THAT THE REQUEST METHOD IS POST

    // HOW TO MAP THE DATA TO THE NOTIFICATION SERVICE
    // THIS IS A FUNCTION THAT TAKES AN ARRAY OF DATA AND RETURNS AN OBJECT CORRESPONDING TO REQUEST BODY
    // NOTE THAT THE OBJECTS IN THE DATA ARRAY FORMAT IS DESCRIBED IN README.md
    DATA_MAPPER: (dataArray) => ({ data: dataArray }),

    // HOW MANY MESSAGES TO COLLECT BEFORE SENDING A NOTIFICATION
    NOTIFY_BATCH_SIZE: 5,

    // WHETHER WE SHOULD LOG CHATS TO STDOUT
    LOG_CHAT: true,
}

